import Head from 'next/head'
import DefaultLayout from '@/layouts/DefaultLayout'
import ProfileCard from '@/components/ProfileCard';
import PageHeader from '@/components/PageHeader';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

			<DefaultLayout>
				<PageHeader title="Welkom Jane Doe" />
				<div className="contactList">
					<h3>Jouw kring</h3>
					<div className="cards">
						<ProfileCard />
						<ProfileCard />
						<ProfileCard />
						<ProfileCard />
						<ProfileCard />
						<ProfileCard />
					</div>
				</div>
			</DefaultLayout>

    </div>
  )
}
