import DefaultLayout from '@/layouts/DefaultLayout'
import Head from 'next/head'
import PageHeader from '@/components/PageHeader';
import GameCard from '@/components/GameCard';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

			<DefaultLayout>
				<PageHeader title="Welkom Jane Doe" />
				<div className="cards">
					<GameCard />
					<GameCard />
					<GameCard />
					<GameCard />
				</div>
			</DefaultLayout>

    </div>
  )
}
